
export const products = [
    {
        id: "peace-lily",
        title: "Peace Lily",
        description: "Air Purifying Indoor Plant",
        price: 189,
        url: "/",
        loved: false,
        offer: "Free Pot",
        rating: 4.3,
        thumbnail: "https://images.pexels.com/photos/3125197/pexels-photo-3125197.jpeg?w=200",
        small: true,
    },
    {
        id: "monstera-deliciosa",
        title: "Monstera Deliciosa",
        description: "Trending Indoor Plant",
        price: 399,
        url: "/",
        loved: true,
        offer: "Limited Stock",
        rating: 4.7,
        thumbnail: "https://images.pexels.com/photos/6297088/pexels-photo-6297088.jpeg?w=200",
    },
    {
        id: "string-of-pearls",
        title: "String of Pearls",
        description: "Hanging Succulent",
        price: 159,
        url: "/",
        loved: true,
        offer: "New Arrival",
        rating: 4.6,
        thumbnail: "https://images.pexels.com/photos/1903964/pexels-photo-1903964.jpeg?w=200",
    },
    {
        id: "calathea",
        title: "Calathea",
        description: "Prayer Plant",
        price: 279,
        url: "/",
        loved: false,
        offer: "25% off",
        rating: 4.5,
        thumbnail: "https://images.pexels.com/photos/6297385/pexels-photo-6297385.jpeg?w=200",
    },
    {
        id: "rubber-plant",
        title: "Rubber Plant",
        description: "Air Purifying",
        price: 339,
        url: "/",
        loved: true,
        offer: "Premium Quality",
        rating: 4.6,
        thumbnail: "https://images.pexels.com/photos/6297089/pexels-photo-6297089.jpeg?w=200",
    },
    {
        id: "desert-cactus",
        title: "Desert Cactus",
        description: "Succulent Collection",
        price: 199,
        url: "/",
        loved: true,
        offer: "Gift Ready",
        rating: 4.8,
        thumbnail: "https://images.pexels.com/photos/1903965/pexels-photo-1903965.jpeg?w=200",
    },
    {
        id: "japanese-maple",
        title: "Japanese Maple",
        description: "Exotic Outdoor Plant",
        price: 699,
        url: "/",
        loved: true,
        offer: "15% off",
        rating: 4.8,
        thumbnail: "https://images.pexels.com/photos/1146708/pexels-photo-1146708.jpeg?w=200",
    },
    {
        id: "lavender-plant",
        title: "Lavender Plant",
        description: "Fragrant Herb",
        price: 199,
        url: "/",
        loved: true,
        offer: "5% off",
        rating: 4.3,
        thumbnail: "https://images.pexels.com/photos/6208086/pexels-photo-6208086.jpeg",
    },
    {
        id: "jade-plant",
        title: "Jade Plant",
        description: "Low Maintenance",
        price: 299,
        url: "/",
        loved: false,
        offer: "New Arrival",
        rating: 4.1,
        thumbnail: "https://images.pexels.com/photos/6597559/pexels-photo-6597559.jpeg",
    },
    {
        id: "money-plant",
        title: "Money Plant",
        description: "Brings Good Luck",
        price: 99,
        url: "/",
        loved: true,
        offer: "10% off",
        rating: 4.6,
        thumbnail: "https://images.pexels.com/photos/3644742/pexels-photo-3644742.jpeg",
    },
];

export const plants = [
    {
        images: ["https://images.pexels.com/photos/3125197/pexels-photo-3125197.jpeg?w=200"],
        title: "Peace Lily",
        description: "Air Purifying Indoor Plant",
        price: 189,
        offer: "Free Pot",
        rating: 4.3,
        productKey: "PL-001",
        tags: ["indoor", "air-purifying", "low-maintenance", "flowering", "home-decor"],
        stocks: 50,
        available: true,
        createdAt: new Date("2023-01-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Height", value: "30 cm" },
            { key: "Light", value: "Low to Medium" },
            { key: "Watering", value: "Once a week" },
            { key: "Pet Friendly", value: "No" },
        ],
        features: ["Air purifying", "Low maintenance", "Improves indoor air quality", "Beautiful white flowers"],
    },
    {
        images: ["https://images.pexels.com/photos/6297088/pexels-photo-6297088.jpeg?w=200"],
        title: "Monstera Deliciosa",
        description: "Trending Indoor Plant",
        price: 399,
        offer: "Limited Stock",
        rating: 4.7,
        productKey: "MD-002",
        tags: ["indoor", "trending", "tropical", "large-leaves", "home-decor"],
        stocks: 30,
        available: true,
        createdAt: new Date("2023-02-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Height", value: "50 cm" },
            { key: "Light", value: "Medium to Bright" },
            { key: "Watering", value: "Twice a week" },
            { key: "Pet Friendly", value: "No" },
        ],
        features: ["Unique leaf shape", "Easy to care for", "Adds a tropical vibe", "Grows quickly"],
    },
    {
        images: ["https://images.pexels.com/photos/1903964/pexels-photo-1903964.jpeg?w=200"],
        title: "String of Pearls",
        description: "Hanging Succulent",
        price: 159,
        offer: "New Arrival",
        rating: 4.6,
        productKey: "SP-003",
        tags: ["succulent", "hanging", "low-maintenance", "unique", "home-decor"],
        stocks: 20,
        available: true,
        createdAt: new Date("2023-03-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Length", value: "60 cm" },
            { key: "Light", value: "Bright Indirect" },
            { key: "Watering", value: "Once every 2 weeks" },
            { key: "Pet Friendly", value: "No" },
        ],
        features: ["Unique appearance", "Drought-tolerant", "Perfect for hanging baskets", "Low maintenance"],
    },
    {
        images: ["https://images.pexels.com/photos/6297385/pexels-photo-6297385.jpeg?w=200"],
        title: "Calathea",
        description: "Prayer Plant",
        price: 279,
        offer: "25% off",
        rating: 4.5,
        productKey: "CA-004",
        tags: ["indoor", "prayer-plant", "ornamental", "pet-friendly", "home-decor"],
        stocks: 40,
        available: true,
        createdAt: new Date("2023-04-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Height", value: "40 cm" },
            { key: "Light", value: "Medium" },
            { key: "Watering", value: "Twice a week" },
            { key: "Pet Friendly", value: "Yes" },
        ],
        features: ["Ornamental leaves", "Pet-friendly", "Leaves move with light", "Improves humidity"],
    },
    {
        images: ["https://images.pexels.com/photos/6297089/pexels-photo-6297089.jpeg?w=200"],
        title: "Rubber Plant",
        description: "Air Purifying",
        price: 339,
        offer: "Premium Quality",
        rating: 4.6,
        productKey: "RP-005",
        tags: ["indoor", "air-purifying", "low-maintenance", "glossy-leaves", "home-decor"],
        stocks: 25,
        available: true,
        createdAt: new Date("2023-05-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Height", value: "70 cm" },
            { key: "Light", value: "Bright Indirect" },
            { key: "Watering", value: "Once a week" },
            { key: "Pet Friendly", value: "No" },
        ],
        features: ["Air purifying", "Low maintenance", "Glossy leaves", "Adds elegance to any space"],
    },
    {
        images: ["https://images.pexels.com/photos/1903965/pexels-photo-1903965.jpeg?w=200"],
        title: "Desert Cactus",
        description: "Succulent Collection",
        price: 199,
        offer: "Gift Ready",
        rating: 4.8,
        productKey: "DC-006",
        tags: ["succulent", "desert", "low-maintenance", "drought-tolerant", "home-decor"],
        stocks: 15,
        available: true,
        createdAt: new Date("2023-06-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Height", value: "20 cm" },
            { key: "Light", value: "Bright Direct" },
            { key: "Watering", value: "Once a month" },
            { key: "Pet Friendly", value: "No" },
        ],
        features: ["Drought-tolerant", "Unique shapes", "Perfect for desks", "Low maintenance"],
    },
    {
        images: ["https://images.pexels.com/photos/1146708/pexels-photo-1146708.jpeg?w=200"],
        title: "Japanese Maple",
        description: "Exotic Outdoor Plant",
        price: 699,
        offer: "15% off",
        rating: 4.8,
        productKey: "JM-007",
        tags: ["outdoor", "exotic", "ornamental", "seasonal", "garden"],
        stocks: 10,
        available: true,
        createdAt: new Date("2023-07-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Height", value: "100 cm" },
            { key: "Light", value: "Partial Shade" },
            { key: "Watering", value: "Twice a week" },
            { key: "Pet Friendly", value: "Yes" },
        ],
        features: ["Ornamental foliage", "Seasonal color change", "Perfect for gardens", "Adds a focal point"],
    },
    {
        images: ["https://images.pexels.com/photos/6208086/pexels-photo-6208086.jpeg"],
        title: "Lavender Plant",
        description: "Fragrant Herb",
        price: 199,
        offer: "5% off",
        rating: 4.3,
        productKey: "LP-008",
        tags: ["herb", "fragrant", "medicinal", "outdoor", "garden"],
        stocks: 35,
        available: true,
        createdAt: new Date("2023-08-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Height", value: "30 cm" },
            { key: "Light", value: "Full Sun" },
            { key: "Watering", value: "Once a week" },
            { key: "Pet Friendly", value: "Yes" },
        ],
        features: ["Aromatic", "Medicinal uses", "Attracts pollinators", "Calming fragrance"],
    },
    {
        images: ["https://images.pexels.com/photos/6597559/pexels-photo-6597559.jpeg"],
        title: "Jade Plant",
        description: "Low Maintenance",
        price: 299,
        offer: "New Arrival",
        rating: 4.1,
        productKey: "JP-009",
        tags: ["succulent", "low-maintenance", "good-luck", "indoor", "home-decor"],
        stocks: 20,
        available: true,
        createdAt: new Date("2023-09-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Height", value: "25 cm" },
            { key: "Light", value: "Bright Indirect" },
            { key: "Watering", value: "Once every 2 weeks" },
            { key: "Pet Friendly", value: "No" },
        ],
        features: ["Symbol of good luck", "Easy to care for", "Thick, glossy leaves", "Long-lasting"],
    },
    {
        images: ["https://images.pexels.com/photos/3644742/pexels-photo-3644742.jpeg"],
        title: "Money Plant",
        description: "Brings Good Luck",
        price: 99,
        offer: "10% off",
        rating: 4.6,
        productKey: "MP-010",
        tags: ["indoor", "luck", "air-purifying", "low-maintenance", "home-decor"],
        stocks: 60,
        available: true,
        createdAt: new Date("2023-10-01"),
        updatedAt: new Date("2023-10-01"),
        specifications: [
            { key: "Height", value: "40 cm" },
            { key: "Light", value: "Low to Medium" },
            { key: "Watering", value: "Once a week" },
            { key: "Pet Friendly", value: "Yes" },
        ],
        features: ["Air purifying", "Symbol of prosperity", "Easy to grow", "Adapts to low light"],
    },
];
